# House Price Prediction

A Machine Learning project that predicts house prices using Linear Regression.

In [2]:
import pandas as pd
import seaborn as sns

## 1. Objective

The objective of this project is to build a Machine Learning model that can predict house prices based on different features of a house.

In this project, Linear Regression is used to understand the relationship between house features and their SalePrice.

## 2. Dataset

The dataset used for this project is the House Prices dataset.

It contains information about different houses, including features such as lot area, overall condition, year built, basement area, and other property characteristics.

The target variable is `SalePrice`, which represents the sale price of the house.

The dataset contains 2919 rows and 13 columns.

In [3]:
hpp = pd.read_csv("../data/HousePricePrediction (1).csv")

In [4]:
hpp

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

## 3. Features Used

The following numerical features were used as input variables for the Linear Regression model:

- `MSSubClass`
- `LotArea`
- `OverallCond`
- `YearBuilt`
- `YearRemodAdd`
- `BsmtFinSF2`
- `TotalBsmtSF`

The `Id` column was removed because it is only an identifier and does not provide useful information for predicting house prices.

Categorical columns were also removed for this first draft model because Linear Regression requires numerical input.

## 4. Target Variable

The target variable for this project is `SalePrice`.

`SalePrice` represents the actual selling price of each house. The Linear Regression model uses the selected house features to predict this value.

## 5. Data Preparation

The dataset was inspected to understand its structure, data types, and missing values.

For the first draft model, the first 1460 rows containing `SalePrice` were used.

The `Id` column was removed because it is only an identifier. Categorical columns such as `MSZoning`, `LotConfig`, `BldgType`, and `Exterior1st` were also removed because this first model uses only numerical features.

The data was then divided into input features (`X`) and the target variable (`y`).

In [11]:
X = hpp.drop(columns=["Id", "MSZoning", "LotConfig", "BldgType", "Exterior1st", "SalePrice"])
y = hpp["SalePrice"]

In [20]:
hpp_train = hpp.iloc[:1460]

X = hpp_train.drop(columns=["Id", "MSZoning", "LotConfig", "BldgType", "Exterior1st", "SalePrice"])
y = hpp_train["SalePrice"]

In [21]:
X.shape
y.shape

(1460,)

## 6. Train-Test Split

The dataset was divided into training and testing sets using an 80:20 ratio.

- 80% of the data was used for training the model.
- 20% of the data was used for testing the model.
- `random_state=42` was used to make the split reproducible.

The training set contains 1168 observations, while the testing set contains 292 observations.

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,Y,test_size = 0.2, random_state = 42
)

In [23]:
X_test.head()

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
892,20,8414,8,1963,2003,0.0,1059.0
1105,60,12256,5,1994,1995,0.0,1463.0
413,30,8960,6,1927,1950,0.0,1008.0
522,50,5000,7,1947,1950,0.0,1004.0
1036,20,12898,5,2007,2008,0.0,1620.0

## 7. Model Used

Linear Regression was used as the first Machine Learning model for this project.

The model was trained using the training data and then used to predict house prices for the test data.

In [24]:
#model training
from sklearn.linear_model import LinearRegression

#make model by call function
model = LinearRegression()

#for training we willl fit the model and passes values 
model.fit(X_train, y_train)

LinearRegression()

In [25]:
#use this model for predictions
y_pred = model.predict(X_test)

In [26]:
y_pred

array([202471.14355514, 233382.55759054, 120266.43362241, 134204.44870426,
       263068.97913763, 127534.41848927, 186507.12324987, 157497.16021453,
       124665.35715052, 142549.68757674, 113602.16038019, 150911.51331302,
       115722.10826879, 247093.72450427, 197055.4906725 , 190241.49041048,
       197019.83109241, 188968.62105331, 109914.72602716, 241461.05736522,
       170143.89260832, 198514.5752892 , 191443.05920784, 172983.7426645 ,
       232049.74048997, 209502.53238224, 237098.60871826, 130536.13466836,
       196755.87601707, 236792.84966334, 118034.16570067, 210712.60491946,
       214975.86018618, 143620.72167937, 261608.75931387, 165715.80033828,
       157273.32135057, 196877.26709616, 235620.91552785,  67178.32603341,
       108274.0171945 , 197848.04662168, 149886.46748084, 295360.88104409,
       144131.23253388,  83427.02077039, 127865.67814164, 157855.59801492,
       273702.64973014, 134279.16535488, 125657.57062283, 210303.63194189,
       117117.95201033, 212205.81227824, 196127.39625048, 266193.64976754,
       174552.45603562, 188045.2321841 , 167128.77848286, 116280.27927866,
        81416.15462097, 180069.09443014, 221691.91844001, 256610.6720597 ,
       272533.72098584, 202461.42823317, 110353.71287673, 247246.0156147 ,
       189364.50962515, 180469.27373249,  98182.33133405, 139538.22309211,
       136322.50000893,  51258.09363112, 318261.77899794, 215953.62263575,
       229748.07227428, 218791.0740054 , 145705.56571072, 153282.53565389,
       168061.41655896,  90138.31105448, 147049.30853742, 114758.13528266,
       156845.30421868, 158791.94471439, 221536.12726236, 214834.52863328,
       196124.01468705, 194976.04117898, 192725.97007717, 137459.13757916,
       172025.57253685, 191033.30782849, 216083.86215034, 234750.56501894,
       169521.86159454, 178244.64609107, 247333.69441652, 178350.23179532,
       197951.86120826, 198673.83208899, 262524.37175466, 161954.23173989,
       209451.5228998 , 147261.44526475, 194897.69978436, 236054.82296472,
       193339.44734382, 163572.069033  ,  51012.75841702, 171475.62982041,
       204891.64149094, 168152.40808177, 208394.98753053, 152423.49845388,
       174428.86338653, 147552.84925611,  98853.46069951, 361062.7114929 ,
       174659.43281524, 196127.39625048, 192815.4523038 , 159947.71888941,
       215608.10766301, 147868.86493842, 199939.22398271, 111922.63855747,
       217524.12181168, 157015.29420529, 191958.91778601, 276694.40963716,
       192457.31233248,  90780.40922272,  77570.82385033, 266968.51362872,
       269733.7324622 , 159978.20700044, 251891.98224436, 321574.13810048,
       238041.64402897, 185857.69505969, 162628.43090976, 126469.0799164 ,
       176033.76025186, 144587.35531761, 168230.91771425, 242763.27082875,
       188219.88545969,  84157.1881463 ,  91952.3627218 , 126654.54672626,
       245348.40074515, 156392.51980736, 106872.30349993, 158872.36754941,
       172445.17800387, 163146.52008112, 132058.80049766, 159964.61474819,
       231728.67057787, 177262.25383387, 260584.74488742, 198445.29170373,
       114267.64479827, 199310.1122711 , 196480.95565086, 250188.4197089 ,
       292883.8994232 , 154464.20317666, 276838.85461209, 130684.59917688,
       111652.05103948, 142514.00081123, 250477.46486272,  72408.36558171,
       100608.13247094, 206099.70760032, 150270.08870444, 182683.87669519,
       215808.80248284,  96446.81707474, 164481.46422241, 148700.0481583 ,
       214114.50838905,  88242.33717846, 251362.78696957, 236001.98213991,
       239556.74376659, 122591.77225304, 140085.96559996, 133162.56234206,
       114843.90474567, 184159.49164533, 232347.72305433, 179804.05867555,
       225682.24886279,  79759.38446642, 198405.23517123,  95749.74279256,
       273528.83687732, 193224.14002343, 141931.36701323, 235512.31647808,
       230435.71877242, 144867.28801227, 206623.31185524, 161212.01427608,
       161685.92900498, 141907.17917732, 172721.5400001 , 141790.3664664 ,
       137664.77520418, 180469.27373249, 229188.6001256 , 255312.60820492,
       229534.55466692, 152811.25661386, 132694.99370945,  98716.39640398,
       158145.20741625, 236123.43729285, 206290.87324547, 101648.10020603,
       246391.75884553, 205406.59760865,  81298.31521211, 146416.91444352,
       183946.46667047,  99169.39041844, 114331.25248945, 170427.84325341,
       134707.75332593, 161162.14285766, 186236.27727299, 143854.10539063,
       224984.8297279 , 193976.65960628, 204356.44209293, 167531.61878444,
       149809.65390649, 183175.5607991 , 213505.34696466, 248025.44816856,
       163577.28030936, 164773.683351  , 155689.63816281, 200950.42498894,
       179662.54240344, 103933.04553663, 205990.14014754, 148876.81498995,
       142558.06578774,  88693.61193765, 160964.04827086, 171861.19330071,
       159519.44710794, 142587.48415944, 172173.14175459, 214457.69221839,
       285365.01089148, 191128.80482952, 150797.22933102, 230679.27931481,
       266061.07507285, 212604.36217279, 215893.23746389, 195516.3889965 ,
       137027.98860297, 157936.98270397, 295354.08470017, 216834.05844573,
       220188.55094384, 115298.12340986,  76136.5962954 , 162776.81070803,
       204810.43168303, 279458.24592516, 252103.42162745, 127376.09947409,
       207604.74608369, 140390.16723873, 194707.22362377, 161161.53296764,
       266769.8255569 , 201678.59898128, 204921.15300724, 164924.06652832,
       256282.04501408, 190218.63404326, 105970.3360133 , 157527.33647572])

## 8. Evaluation Results

The model was evaluated using four metrics:

- **MAE (Mean Absolute Error):** 37,871.43
- **MSE (Mean Squared Error):** 3,259,194,958.46
- **RMSE (Root Mean Squared Error):** 57,089.36
- **R² Score:** 0.5751

The R² score indicates that the model explains approximately 57.5% of the variation in house prices.

In [27]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("r-squared : ",r2)

n = X_test.shape[0]
p = X_test.shape[1]

adjusted_r2 = 1- ((1-r2)*(n-1)/ (n-p-1))
print("adjusted_r2 : ",adjusted_r2)

r-squared :  0.5750904367788159
adjusted_r2 :  0.564617313741674

In [29]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

MAE: 37871.42885084627

In [30]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

MSE: 3259194958.4598827

In [31]:
import numpy as np

rmse = np.sqrt(mse)

RMSE: 57089.35941539266

## 9. Improved Model - Feature Preprocessing

In [35]:
X2 = hpp_train[[
    "MSSubClass",
    "MSZoning",
    "LotArea",
    "LotConfig",
    "BldgType",
    "OverallCond",
    "YearBuilt",
    "YearRemodAdd",
    "Exterior1st",
    "BsmtFinSF2",
    "TotalBsmtSF"
]]

y2 = hpp_train["SalePrice"]

In [37]:
X2.shape

(1460, 11)

In [38]:
X2.select_dtypes(include="object").columns

Index(['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st'], dtype='object')

In [39]:
from sklearn.preprocessing import OneHotEncoder

X2 = pd.get_dummies(X2, drop_first=True)

In [40]:
X2.shape

(1460, 33)

In [41]:
X2.isnull().sum()

MSSubClass             0
LotArea                0
OverallCond            0
YearBuilt              0
YearRemodAdd           0
BsmtFinSF2             0
TotalBsmtSF            0
MSZoning_FV            0
MSZoning_RH            0
MSZoning_RL            0
MSZoning_RM            0
LotConfig_CulDSac      0
LotConfig_FR2          0
LotConfig_FR3          0
LotConfig_Inside       0
BldgType_2fmCon        0
BldgType_Duplex        0
BldgType_Twnhs         0
BldgType_TwnhsE        0
Exterior1st_AsphShn    0
Exterior1st_BrkComm    0
Exterior1st_BrkFace    0
Exterior1st_CBlock     0
Exterior1st_CemntBd    0
Exterior1st_HdBoard    0
Exterior1st_ImStucc    0
Exterior1st_MetalSd    0
Exterior1st_Plywood    0
Exterior1st_Stone      0
Exterior1st_Stucco     0
Exterior1st_VinylSd    0
Exterior1st_Wd Sdng    0
Exterior1st_WdShing    0
dtype: int64

In [42]:
y2.isnull().sum()

np.int64(0)

## 10. Train-Test Split for Improved Model

In [43]:
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, y2, test_size=0.2, random_state=42
)

## 11. Improved Linear Regression Model

In [46]:
model2 = LinearRegression()

model2.fit(X2_train, y2_train)

LinearRegression()

## 12. Predictions and Evaluation

In [47]:
y2_pred = model2.predict(X2_test)

In [48]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae2 = mean_absolute_error(y2_test, y2_pred)
mse2 = mean_squared_error(y2_test, y2_pred)
rmse2 = np.sqrt(mse2)
r2_2 = r2_score(y2_test, y2_pred)

print("MAE:", mae2)
print("MSE:", mse2)
print("RMSE:", rmse2)
print("R²:", r2_2)

MAE: 34122.85443215004
MSE: 2918458029.585536
RMSE: 54022.75473895732
R²: 0.6195131796544807

## 13. Model Comparison

The baseline Linear Regression model achieved an R² score of 0.5751.

After including the categorical features using one-hot encoding, the improved model achieved an R² score of 0.6195.

The improved model also had lower MAE, MSE, and RMSE values than the baseline model.

Therefore, Model 2 performed better than the baseline Model 1.

## 14. Conclusion

A Linear Regression model was successfully developed to predict house prices using the given house features.

The baseline model achieved an R² score of 0.5751. After preprocessing the categorical features using one-hot encoding, the improved model achieved an R² score of 0.6195.

The improved model also achieved lower MAE and RMSE values compared to the baseline model. Therefore, including the categorical features improved the performance of the Linear Regression model.

This project demonstrates how data preprocessing and feature representation can improve the performance of a Machine Learning regression model.